-- 1.

SELECT STUDENT_NO 학번 , STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') AS 입학년도 
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 입학년도;


-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';


-- 3.
SELECT PROFESSOR_NAME 교수이름, 
TO_CHAR(TO_DATE(TO_CHAR(SYSDATE, 'YYMMDD'), 'RRMMDD'), 'YYYY') - 
 TO_CHAR(TO_DATE('19' || SUBSTR(PROFESSOR_SSN, 1, 2), 'YYYY'), 'YYYY') 나이
FROM TB_PROFESSOR 
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 나이;


-- 4.
SELECT SUBSTR(PROFESSOR_NAME, 2) 이름
FROM TB_PROFESSOR;

-- 5. 
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT;